export const cityname = document.getElementById("cityname");
export const date = document.getElementById("current-date");
export const currTemp = document.getElementById("curr-temp");
export const apparentTemp = document.getElementById("apparent-temp");
export const humidity = document.getElementById("humidity");
export const wind = document.getElementById("wind");
export const precipitation = document.getElementById("precipitation");
export const input = document.getElementById("search");
export const searchBtn = document.getElementById("search-button");
export const hourlyContainer = document.getElementById("hourly-container");
export const dailyContainer = document.getElementById("daily-container");
export const daySelect = document.getElementById("day-select");
export const unitToggle = document.getElementById("unitToggle"); 
export const weatherStatus = document.getElementById("weather-status-id");
export const unitsBtn = document.getElementById("unitsBtn");
export const unitsMenu = document.getElementById("unitsMenu");
export const tempUnitRadios = document.querySelectorAll(
    'input[name="tempUnit"]'
  );